### PR TITLE
changed regex to a-z because the id can also contain more than a-f chars

### PR DESCRIPTION
**Pull request by cli-ish**
While my setup testing I came across a problem with some ids which were not correctly validated by the auth.py so I checked the regex parts and it seems that there can be more than a-f chars so I put the limit to a-z and now it works fine for me.

Is there any wiki entry which certains that a-f was correct?

### CODE REVIEW

**Comment by ichdasich** [comment]
The bbbid we are matching on is a combination of a sha1 of the extMeetingId (`bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java`, l641) and a unix timestamp. The former is strictly a-f0-9, the latter strictly 0-9; Do you have an example of a meeting id that was not matched?

**Comment by cli-ish** [comment]
Yeah, you are right. There is still one problem with the meetingid:
bbbid: 1b3ffdff81d8246aaf1e92b93380a67bae80589b-1594896576930
meetingId: zgqn49igpydht6vhqk7mqoq6jeaauoa7nhy7th4t

So only my line from gl-auth/auth-passwd-bbb.py
`re_bbbid = re.compile(r'[a-z0-9]{40}')`
is need to patch that issue.

**Comment by ichdasich** [comment]
But... where is the meetingid used in the URL? Can you maybe share a `find` for the affected recording's directory?

**Comment by cli-ish** [comment]
I will create a new pull request, it seems that i have confused you with a part of my pull which is not needed anymore because you are right with the bbbid, this still do not apply for teh filter you have at the line

**Pull request closed without merging**
